### ISSUE TITLE
Question about the training environment.

### ISSUE THREAD

**Issue by Jintopia** [primecai/Pix2NeRF#10]
Hi, First of all, I was impressed with your paper.
I read your paper in CVPR 2022 , but it doesn't mention about training environment and time. Can i get information about it?
if you are reluctant to disclose, plz contact me email or other connection

**Comment by primecai** [comment]
Hi,

Many thanks for the interest. Please refer to section 4.1 Technical details part of our paper. We optimize all models for 300k iterations, which is approximately 2-3 days using 4 GTX1080Ti GPUs with DDP.

Best regards.

**Comment by Jintopia** [comment]
Thanks
