### ISSUE TITLE
The question about the re-train the pix2nerf.

### ISSUE THREAD

**Issue by liustu** [primecai/Pix2NeRF#13]
Hi, I have re-train the pix2nerf with a single 3090 GPU on synchairs, but I have not achieve the view synthesis under the condition of a single view. If I utilize a single 3090 GPU to train the pix2nerf, would I change the batch size from 9 to 36? Thank you very much.

**Comment by primecai** [comment]
Hi,

Yes, please increase the batch size to as high as possible if you are training on a single GPU---our backbone pi-GAN is somewhat sensible to small batch sizes.
Meanwhile, do you have any qualitative result? Training with one GPU should give some reasonable results. Is the unconditional generation working?
Note that I made a mistake in the README file for the training command, make sure you are using the correct configuration file by setting `--curriculum=srnchairs`. Sorry for this if this made things confusing.

**Comment by liustu** [comment]
Hi, if I am training on a single GPU, the unconditional generation does not work with the orginal setting of the batch size 9 . Now, I have change the batch size from 9 to 36, and batch_split from 3 to 6 for training the pix2nerf on a single 3090 GPU. By the way, for verifing the results of the re-trained model, would you like to provide a '.py' to obtain the quantitative results?

**Comment by primecai** [comment]
Hi,

May I ask how many iterations did you train? Here are some single shot NVS results I got from 30k iterations, train with original batch size & split on 1 GPU.

![30381a38-5624-4d3c-a59f-478ecc8cd2eb](https://user-images.githubusercontent.com/43519981/185334995-fd15fda9-7748-4a0b-8cb0-ed0062cb0f13.png)


![c6bd3c2c-9897-473b-be17-97d1f49224b6](https://user-images.githubusercontent.com/43519981/185334815-410fb50a-28e9-4d8d-a031-507fe5ad6def.png)

Top input, Bottom NVS.

**Comment by liustu** [comment]
Hi, I have trained the pix2nerf for 30K iterations. and I got simiar results as your above results. However, the novel views in the recon.png are different from the input.png. Besides, I test the trained model by utilizing the "reder_video_from_img.py', but I can't obtain the accurate novel views according to the input source view. I don't know whether the batch size influnce the training of the pix2nerf. Now, I change the batch size from 9 to 36 and batch split from 3 to 6 for re-training the pix2nerf. In 12000 iterations, I got the following results.
![12000_input](https://user-images.githubusercontent.com/55391927/185337540-6f2a1182-302c-4889-81f4-278c76737ac9.png)
![12000_recon](https://user-images.githubusercontent.com/55391927/185337565-c0f22f7c-0136-48ed-8979-9da9ab218446.png)
I still can not get the accurate novel views according to the input source view. Would you like to tell me why? Thank you very much.

**Comment by primecai** [comment]
Hi,

I think 30k iterations is way too few. Note that our full training is 300k iterations and 30k iterations does not even pass the first stage of progressive training. I never tried to train a model for the full 300k iterations with small batch sizes, but it should not affect that much. I'll do some experiments on this as well.

Best.

**Comment by liustu** [comment]
Hi,
sorry for my mistake of the whole iterations.I have trained the pix2nerf for 300k iterations. Now I have increase the batch size to tr-train the network. Would the input.png abd recon.png are corresponding? How can I know the trained pix2nerf obtains accurate results during the training? Thank you very much.



---Original---
From: "Prime ***@***.***&gt;
Date: Thu, Aug 18, 2022 16:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [primecai/Pix2NeRF] The question about the re-train the pix2nerf.(Issue #13)




 
Hi,
 
I think 30k iterations is way too few. Note that our full training is 300k iterations and 30k iterations does not even pass the first stage of progressive training. I never tried to train a model for the full 300k iterations with small batch sizes, but it should not affect that much. I'll do some experiments on this as well.
 
Best.

**Comment by primecai** [comment]
Yes they should correspond, there could still be some errors for the pose estimation (our PSNR results were affected quite a bit by this), but they should look reasonable.
Do you have qualitative results from your 300k iteration model?
Results should look ok after ~100k iterations. I will be quite surprised if your end results are similar to my 30k iteration model, even if it was trained on lower batch size.

**Comment by liustu** [comment]
Ok, thank you very much. I have deleted the last trained model. I will re-train the pix2nerf with batch size of 36. Thank you again.



---Original---
From: "Prime ***@***.***&gt;
Date: Thu, Aug 18, 2022 16:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [primecai/Pix2NeRF] The question about the re-train the pix2nerf.(Issue #13)




 
Yes they should correspond, there could still be some errors for the pose estimation (our PSNR results were affected quite a bit by this), but they should look reasonable.
 Do you have qualitative results from your 300k iteration model?
 Results should look ok after ~100k iterations. I will be quite surprised if your end results are similar to my 30k iteration model, even if it was trained on lower batch size.

**Comment by liustu** [comment]
Hi, when I change the batch size from 9 to 36, it looks better than the last result.
input:
![298000_input](https://user-images.githubusercontent.com/55391927/186364519-118c1254-6dc4-41d3-b654-78071885989c.png)
output:
![298000_recon](https://user-images.githubusercontent.com/55391927/186364520-3a8996b5-4a5a-431f-b9b6-16f1ad991fb8.png)
Do you think the above results are resonable?
In addition I don't know whether the results of mine is same to your results of the paper. Would you like to provide the evaluation script to help for obtaining the quantitative results? Thank you!

**Comment by primecai** [comment]
Hi,

It looks relatively reasonable, perhaps a little bit converging towards a mutual figure? I am doing some verification experiments on this as well---I may have accidentally changed a setting while refactoring the train script.
Regarding evaluation script, please email me for a messy FID/KID/IS script in private. I am not planning to release the PSNR script for now, because I was using a version of PixelNeRF's script and it will require quite some work to make it a clear version to be released---feel free to use PixelNeRF's evaluation scripts though.

Best.
