### ISSUE TITLE
How to know the relationship between pose d

### ISSUE THREAD

**Issue by xiaoxin-Crayon** [primecai/Pix2NeRF#14]
I means that if i know the image of 30°, i could easily get the rendered image of 40° by given a absolute angles of 40°. 
However, i donnot know how the pose d which is a latent code achieve this.
That is, could i modify the latent pose d to get the clear direction?

**Comment by primecai** [comment]
Hi,

I'm not sure if I understand correctly, but the camera pose d corresponds to the actual viewing direction, so explicit control of the camera pose is definitely feasible---that is how we generate trajectories in the rendering videos:
https://github.com/primecai/Pix2NeRF/blob/2e67bbafca68448173f41444b81266500e98a23e/render_video_from_img.py#L106

Best regards.
