### ISSUE TITLE
The question about the re-trained results in celebA

### ISSUE THREAD

**Issue by liustu** [primecai/Pix2NeRF#16]
Hi, I have re-trained the pix2NeRF in a single 3090. I got similar results of IS and FID as your paper but a low result of KID. Would you like to tell me why?
The re-trained results of Pix2NeRF:
{'inception_score_mean': 2.207920169906786, 'inception_score_std': 0.04608231534322652, 'frechet_inception_distance': 28.55671719303598, 'kernel_inception_distance_mean': 0.022525952379879886, 'kernel_inception_distance_std': 0.001017455628829365}
Thank you very much.

**Comment by primecai** [comment]
Hi,

The KID reported in the paper is multiplied by 100---as was done in pi-GAN.

Best regards.

**Comment by liustu** [comment]
Ok，thank you for your reply.



---Original---
From: "Prime ***@***.***&gt;
Date: Sun, Sep 25, 2022 04:14 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [primecai/Pix2NeRF] The question about the re-trained results incelebA (Issue #16)




 
Hi,
 
The KID reported in the paper is multiplied by 100---as was done in pi-GAN.
 
Best regards.
