### ISSUE TITLE
Use the pretrain model to producing multi-view images of pubilc datasets

### ISSUE THREAD

**Issue by whxueChris** [primecai/Pix2NeRF#18]
Hello, thanks for sharing your great job!
Can we use the pretrain model to generate multi-views images with the background? e.g. like this
![000001](https://user-images.githubusercontent.com/50388024/210473152-bc65fda6-468f-497e-bf3a-3a41e57e8926.jpg)
Thanks for your suggestions!

**Comment by primecai** [comment]
Hi,

This is not the purpose of Pix2NeRF as it is a categorical model which is not designed to work well with in the wild images.

Best regards,
Shengqu
