### ISSUE TITLE
About the CelebA_pos.csv?

### ISSUE THREAD

**Issue by Lxiangyue** [primecai/Pix2NeRF#19]
Hi, many thanks for your great work！

May I ask you a question? 
- What is the 'CelebA_pos.csv' used for in the training phase? 
- Is it compulsory in training？ If not, how to remove it?

**Comment by primecai** [comment]
Hi,

The file 'CelebA_pos.csv' is some leftover junk from other things I have tried, it merely saves the filenames in the final framework and can be safely removed.
To remove this, simply replace the csv reading code (https://github.com/primecai/Pix2NeRF/blob/2e67bbafca68448173f41444b81266500e98a23e/datasets.py#L31) with vanilla path listing code (https://github.com/primecai/Pix2NeRF/blob/2e67bbafca68448173f41444b81266500e98a23e/datasets.py#L63) should do.

Best regards,
Shengqu
