### ISSUE TITLE
The question about how to train the Pixel2nerf?

### ISSUE THREAD

**Issue by liustu** [primecai/Pix2NeRF#6]
There is no 'train.py'. Would you like to tell me how to train the pixel2nerf? Thank you.

**Comment by liustu** [comment]
> Hi,
> 
> Firstly, our model is "Pix2NeRF", "PixelNeRF" refers to Alex Yu's work on single view NVS by projecting and decoding 2D features extracted from the input, see https://alexyu.net/pixelnerf/. Back to training, we are still cleaning up the training script, and for legal reasons I am only able to release it after CVPR presentation and making sure results can be duplicated with a single command, this process will take some time. I will try to release it as soon as possible.
> 
> Best regards, Shengqu

Ok, Thank you for your reply, Shengqu. I will wait the training script  for re-training the Pixel2NeRF. Thank you again.

**Comment by primecai** [comment]
Hi,

The training script has just been released. But note that it is not fully validated yet due to the very limited resource I have. Please let me know if any of the training protocols is not working as expected!

Best.
