### ISSUE TITLE
Question on the open sourced time of the 'train' script

### ISSUE THREAD

**Issue by viewsnet** [primecai/Pix2NeRF#8]
Hi, thanks for your contributions on "Single Image to Neural Radiance Fields Translation". I want to know when you will open sourced the  "train" script about the pix2nerf? Thank you.

**Comment by viewsnet** [comment]
There is a long time after the presentation of the CVPR 2022. Would the author like to open sourced the 'train script'? There are many researchers waiting for the excellent work of the Pix2NeRF. Thank you.

**Comment by viewsnet** [comment]
Hello, it has been a long time since the presentation of CVPR2022. Does the author also plan to open source the complete code of pix2nerf? If not, I think I'll not be focusing on this site.

**Comment by primecai** [comment]
Hi,

Many thanks for the interest. Please refer to #6 , we are still cleaning the train script!

Best regards.

**Comment by xuanyuzhang21** [comment]
Thanks for your great work! Could you release the 'train' script in the Pix2NeRF? I am looking forward to deepening my understanding for your paper via the code.  Meanwhile, I also hope to conduct further research based on your excellent work. Thanks a lot.

**Comment by viewsnet** [comment]
I wait the released code for another month, but there is no reply. I think the author may do not plan to open sourced the all code, or just open sourced the code after a long time. I have planed to not to wait this author. I advise you do not wait this another.

**Comment by primecai** [comment]
Hi,

The train script has just been released. But note that it is not fully validated yet due to the very limited resource I have. Please let me know if any of the training protocol is not working as expected!

Best.
